planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -0.2381652134852276
    - -1.07147672837887
    - 0.7055267521432877
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -2.828399594922078
    - 0.27601037033898446
    tracking_err_tol: 0.02
