planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -1.1937274073179747
    - 0.4936919061464909
    - 1.2835460015641595
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -3.9876727670853462
    - 3.005934807899377
    tracking_err_tol: 0.02
