controller:
  # HT-MPC Solver Type, lex vs SQP
  type: "HTIDKC"

  # regularization parameter
  ρ: 0.01
  ctrl_rate: 50

  # options
  joint_acc_bound_enabled: True
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: False
  one_inequality_constraint_enabled: True

  # task parameters
  base_tracking:
    κ: 0.3
  ee_tracking:
    κ: 1.0
  joint_angle_bound:
    κ: 0.02
  collision_avoidance:
    κ: 0.02
    safety_margin: 0.05