controller:
  # HT-MPC Solver Type, lex vs SQP
  type: "HTIDKC"

  # regularization parameter
  ρ: 0.01
  ctrl_rate: 100

  # options
  enable_joint_acc_bound: true

  # task parameters
  base_tracking:
    κ: 1.
  ee_tracking:
    κ: 1.
  joint_angle_bound_task:
    κ: 1.