controller:
  # HT-MPC Solver Type, lex vs SQP
  type: "SQP_TOL_SCHEDULE"

  # MPC params
  dt: 0.1
  prediction_horizon: 1.
  HT_MaxIntvl: 1
  ST_MaxIntvl: 1

  mpc_rate: 10 #hz
  cmd_vel_pub_rate: 100 # hz
  soft_cst: True
  penalize_du: True
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: True

  collision_safety_margin: 0.05

  # soft constraints parameters
  xu_soft:
    mu: 0.001
    zeta: 0.008
  collision_soft:
    mu: 0.001
    zeta: 0.008

  # weights for each cost function
  cost_params:
    EEPos3:
      Qk: 1.
      P: 10.
    BasePos2:
      Qk: 1.
      P: 10.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.01
      Qvb: 0.01
      Qua: 0.01
      Qub: 0.01
      Qdua: 0.
      Qdub: 0.1

  # line search parameters
  beta: 0.5
  alpha: 0.05
