controller:
  # HT-MPC Solver Type, lex vs SQP
  type: "SQP_TOL_SCHEDULE"

  # MPC params
  dt: 0.1
  prediction_horizon: 1.
  HT_MaxIntvl: 1
  ST_MaxIntvl: 1

  mpc_rate: 10 #hz
  cmd_vel_pub_rate: 100 # hz
  slack: False
  soft_cst: True
  penalize_du: True

  # soft constraints parameters
  xu_soft:
      mu: 0.00001
      zeta: 0.00008

  # weights for each cost function
  cost_params:
    EEPos3:
      Qk: 5.
      P: 10.
    BasePos2:
      Qk: 5.
      P: 10.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.01
      Qvb: 0.01
      Qua: 0.01
      Qub: 0.01
      Qdua: 0.
      Qdub: 0.1

  # line search parameters
  beta: 0.5
  alpha: 0.05
