controller:
  # HT-MPC Solver Type, lex vs SQP
  type: "HTMPCSQP"

  # MPC params
  dt: 0.1
  prediction_horizon: 1.0
  HT_MaxIntvl: 1
  ST_MaxIntvl: 1
  hierarchy_constraint_type: "HierarchicalTrackingConstraint"    # error, cost_value, cost_value_sum
  ctrl_rate: 10 #hz
  cmd_vel_pub_rate: 100 # hz
  soft_cst: True
  penalize_du: True
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: False
  sdf_collision_avoidance_enabled: True
  ee_upward_constraint_enabled: False
  cst_tol_schedule_enabled: False
  hierarchy_const_tol: 0.01

  collision_safety_margin: 0.05
  ee_upward_deviation_angle_max: 0.20    #rad, 0.26 rad ~ 15 degree

  # soft constraints parameters
  xu_soft:
    mu: 0.001
    zeta: 0.005
  collision_soft:
    mu: 0.0001
    zeta: 0.005
  ee_upward_soft:
    mu: 0.001
    zeta: 0.01

  # weights for each cost function
  cost_params:
    EEPos3:
      Qk: 1.0
      P: 10.
    BasePos2:
      Qk: 1.
      P: 10.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.1
      Qvb: 0.1
      Qua: 0.02
      Qub: 0.1
      Qdua: 0.
      Qdub: 0.1

  # line search parameters
  beta: 0.5
  alpha: 0.05
