controller:
  home: "default"
  sdf_collision_avoidance_enabled: True
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: True
  base_pose_tracking_enabled: True
  ee_pose_tracking_enabled: True
  
  collision_constraint_type: 
    sdf: "SignedDistanceConstraintCBF" # SignedDistanceConstraint or SignedDistanceConstraintCBF 
  type: "NavHTMPCWorld"
  collision_cbf_gamma:
    sdf: 1.0
    
  dt: 0.3
  prediction_horizon: 3
  robot:
    time_discretization_dt: 0.3
    
  cost_params:
    EEPose:
      Qk: [0.2, 0.2, 0.8, 3, 3, 0.2]
      P: [1, 1, 1, 1, 1, 1]
    BasePoseSE2:
      Qk: [0.75, 0.75, 0.25]
      P: [1, 1, 1]
    BaseVel3:
      Qk: [0.3, 0.3, 0.3]
      P: [1, 1, 1]
    Effort:
      Qqa: [0, 0, 0, 0, 0, 0]
      Qqb: [0, 0, 0]
      Qva: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      Qvb: [0.1, 0.1, 0.1]
      Qua: [2, 1.0, 1.25, 0.7, 0.7, 0.8]
      Qub: [1.0, 1.0, 0.75]
      Qdua: [0, 0, 0, 0, 0, 0]
      Qdub: [0.1, 0.1, 0.1]
    slack:
      z: 50  # linear term
      Z: 1    # quadratic term

  acados:
    name: MMSLAMCtrl_NavHTMPCWorldCBF_RTI
    ocp_solver_options:
      nlp_solver_max_iter: 30
      qp_solver_warm_start: 2
      nlp_solver_tol_stat: 5.0e-02
      nlp_solver_tol_eq: 1.0e-02
      nlp_solver_tol_ineq: 3.0e-02
      nlp_solver_tol_comp: 5.0e-04
