controller:
  home: "default"
  sdf_collision_avoidance_enabled: True
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: True
  base_pose_tracking_enabled: True
  # robot parameters
  robot:
    limits:
      input_rate:
        lower: [-10, -10, -10, -80, -80, -80, -80, -80, -80]
        upper: [10, 10, 10, 80, 80, 80, 80, 80, 80]
      input:
        lower: [ -1., -1.0, -0.75, -1.8, -1.8, -2.0, -1.6, -1.6, -1.6 ]
        upper: [ 1.0, 1.0, 0.75, 1.8, 1.8, 2.0, 1.6, 1.6, 1.6 ]
      state:
        lower: [ -10, -10, -2.pi, -0.pi, -1pi, -1pi, -1pi, -1pi, -1pi,
                 -0.4, -0.4, -0.4, -2, -2, -3, -3, -3, -3 ]
        upper: [ 10, 10, 2pi, 1.pi, 0.2, 1pi, 1pi, 1pi, 1pi,
                 0.4, 0.4, 0.4, 2, 2, 3, 3, 3, 3 ]
  collision_constraint_type: 
    sdf: "SignedDistanceConstraint" # SignedDistanceConstraint or SignedDistanceConstraintCBF 
  type: "STMPC"
  collision_cbf_gamma:
    sdf: 1.2
  
  acados:
    name: MMSLAMCtrl
    ocp_solver_options:
      nlp_solver_max_iter: 50
      qp_solver_warm_start: 2
      nlp_solver_tol_stat: 5.0e-02
      nlp_solver_tol_eq: 1.0e-02
      nlp_solver_tol_ineq: 1.0e-02
      nlp_solver_tol_comp: 1.0e-04

include:
  - package: "mmseq_run"
    path: "config/controller/mpc_params/ctrl_slam_Sep19.yaml"