# Integration Test: Path Planning
# Tests: PathPlanner for base + EE path
# This verifies that PathPlanner works

planner:
  tasks:
  - name: Path Planning
    planner_type: PathPlanner
    base_path: [[0, 0, 0], [1.0, 0.2, 0.5], [2.0, 0.5, 1.0], [2.5, 0.4, 1.57]]  # World frame: [x, y, yaw]
    ee_path:
    - [1.5, 0.4, 1.0, -1pi, 0, 0]
    - [1.5, 0.8, 1.0, -1pi, 0, 0]
    - [1, 0.4, 1.5, -0.5pi, 0.5pi, 0]
    - [1.5, 0.4, 1.5, -0.5pi, 0.5pi, 0]
    dt: 1.0
    tracking_pos_err_tol: 0.2

controller:
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: False
  acados:
    name: "TestPathPlanning"

simulation:
  duration: 8

include:
  - package: "mm_run"
    path: "config/robot/thing.yaml"
  - package: "mm_run"
    path: "config/controller/MPC.yaml"
  - package: "mm_run"
    path: "config/sim/simulation.yaml"
  - package: "mm_run"
    path: "config/scene/empty.yaml"

logging:
  log_dir: "test_experiments/base_path"
  log_level: 10
