planner:
  sot_type: "SoTStatic"
  tasks:
  - frame_id: base
    name: Base Position
    planner_type: ROSTrajectoryPlanner
    cruise_speed: 0.35
    yaw_speed: 0.35
    yaw_accel: 100
    tracking_err_tol: 0.4
    ref_traj_duration: 1.5
  - frame_id: base_link
    name: EE_Pose_Baseframe
    planner_type: EEPoseSE3Waypoint
    target_pose: [1.35, 0.17, 0.7, 1.57, 0, 1.57]
    hold_period: 4
    tracking_err_tol: 0.1
simulation:
  duration: 100
  robot:
    home: [-0, 0, -0., 0.25pi, -0.3pi, 0.5pi, -0.25pi, 0.6pi, 0.417pi]

controller:
  home: "default"
  sdf_collision_avoidance_enabled: True
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: True
  base_pose_tracking_enabled: True

  collision_constraint_type:
    sdf: "SignedDistanceConstraintCBF" # SignedDistanceConstraint or SignedDistanceConstraintCBF
  type: "MPC"
  collision_cbf_gamma:
    sdf: 1.2

  acados:
    name: MMSLAMCtrlCBF
    ocp_solver_options:
      nlp_solver_max_iter: 30
      qp_solver_warm_start: 2
      nlp_solver_tol_stat: 5.0e-02
      nlp_solver_tol_eq: 1.0e-02
      nlp_solver_tol_ineq: 1.0e-02
      nlp_solver_tol_comp: 1.0e-04

include:
  - package: "mm_run"
    path: "config/robot/thing.yaml"
  - package: "mm_run"
    path: "config/controller/MPC.yaml"
  - package: "mm_run"
    path: "config/controller/NavMPC.yaml"
  - package: "mm_run"
    path: "config/sim/isaac_sim.yaml"
  - package: "mm_run"
    path: "config/scene/empty.yaml"
  - package: "mm_run"
    path: "config/map/SDF3D.yaml"

logging:
  log_dir: "3d_collision_sdf"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
