controller:
  # local map params
  map:
    default_val: 1.8
    map_coverage: [4, 4, 1.4]     # need to be the same as isaac.launch or mm.launch in slam_ws
    voxel_size: 0.3
    
    filter_enabled: True
    filter_type: "tv"   # gaussian or tv
    guassian_filter_sigma: 10.
    tv_filter_weight: 1.0

    offline_map:
      enabled: False
      path: "/home/tracy/PhD/data/Aug28/exp/map_collection/2_obstacle_new.bag"
  
  
  # Signed Distance Field Type, SDF3D vs SDF2D
  sdf_type: "SDF3DNew"

































  