planner:
  sot_type: "SoTStatic"
  tasks:
    - name: "Base Pos 1"
      planner_type: "BasePosTrajectoryLine"
      frame_id: "base"
      initial_pos: [-0.0, -0.0]
      target_pos: [-1.0, -3.0]
      cruise_speed: 0.5
      tracking_err_tol: 0.25
    - name: "EE Pos 1"
      planner_type: "EESimplePlanner"
      frame_id: "base"
      target_pos: [-2., -3., 0.8 ]
      hold_period: 3.
      tracking_err_tol: 0.02
    - name: "Base Pos 2"
      planner_type: "BasePosTrajectoryLine"
      frame_id: "base"
      initial_pos: [-1.0, -3.0]
      target_pos: [-1.0, 0.]
      cruise_speed: 0.5
      tracking_err_tol: 0.25
    - name: "EE Pos 2"
      planner_type: "EESimplePlanner"
      frame_id: "base"
      target_pos: [-2., 0., 0.8 ]
      hold_period: 3.
      tracking_err_tol: 0.02
    - name: "Base Pos 3"
      planner_type: "BasePosTrajectoryLine"
      frame_id: "base"
      initial_pos: [-1.0, 0.]
      target_pos: [1.0, 3.]
      cruise_speed: 0.5
      tracking_err_tol: 0.25
    - name: "EE Pos 3"
      planner_type: "EESimplePlanner"
      frame_id: "base"
      target_pos: [2., 3., 0.8 ]
      hold_period: 3.
      tracking_err_tol: 0.02


include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/HTMPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/restaurant.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/debug"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info
