planner:
  sot_type: "SoTStatic"
  tasks:
    - name: "EE Pos 1"
      planner_type: "EESimplePlanner"
      frame_id: "EE"
      target_pos: [0., 0., 0.]
      hold_period: 3.
      tracking_err_tol: 0.02
    - name: "Base Pos 1"
      planner_type: "BaseSingleWaypoint"
      frame_id: "base"
      target_pos: [4.0, 0.]
      tracking_err_tol: 0.25


include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/HTMPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/debug"
  log_level: 4 # 0 - not set, 10 - debug, 20 - info
