simulation:
  static_obstacles:
    enabled: True
    items:
    # Examples
    # - name: "cube_1"
    #   type: DynamicCuboid
    #   xyz: [1, -0.5, 0.25]          # Position in world frame
    #   rpy: [0, 0, 1.5]              # [roll, pitch, yaw] in rad
    #   scale: [0.5, 0.5, 0.5]        # [a, b, c]
    #   color: [0, 0, 1.0]            # RGB Channel
    # - name: "cylinder_1"
    #   type: DynamicCylinder
    #   xyz: [-1, 0.5, 0.5]          # Position in world frame
    #   rpy: [0, 0, 0]
    #   scale: [0.25, 0.25, 1.0]       # [ra, rb, h]
    #   color: [0, 0, 1.0]
    - name: object_1
      type: DynamicCuboid
      scale: [0.5, 1.5, 0.7]
      rpy: [0.0, 0.0, 0.023851]
      xyz: [-0.14768600463867188, 1.7200062274932861, 0.35]
      color: [0, 0, 1.0]
    - name: object_2
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -0.52763]
      xyz: [-0.13169360160827637, 3.473076820373535, 0.3]
      color: [0, 0, 1.0]
    - name: object_25
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -0.91968]
      xyz: [0.8950042724609375, 4.42724084854126, 0.9]
      color: [0, 0, 1.0]
    - name: object_3
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -0.91968]
      xyz: [0.8950042724609375, 4.42724084854126, 0.3]
      color: [0, 0, 1.0]
    - name: object_4
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -1.570496]
      xyz: [2.066667318344116, 5.209323406219482, 0.3]
      color: [0, 0, 1.0]
    - name: object_5
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -1.387161]
      xyz: [3.5093467235565186, 5.123955249786377, 0.3]
      color: [0, 0, 1.0]
    - name: object_6
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -3.14159265359]
      xyz: [5.318436145782471, 2.37027645111084, 0.3]
      color: [0, 0, 1.0]
    - name: object_7
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, 0.001366289]
      xyz: [5.316532135009766, 1.703955054283142, 0.3]
      color: [0, 0, 1.0]
    - name: object_8
      type: DynamicCylinder
      scale: [0.35, 0.35, 0.8]
      rpy: [0.0, 0.0, 0.018095636]
      xyz: [5.315879077911377, 0.995131254196167, 0.4]
      color: [0, 0, 1.0]
    - name: object_9
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, 0.01343483]
      xyz: [5.316505508422852, 0.4355142116546631, 0.3]
      color: [0, 0, 1.0]
    - name: object_10
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -0.025504279]
      xyz: [4.116838455200195, -2.066441774368286, 0.3]
      color: [0, 0, 1.0]
    - name: object_11
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, 0.021549786]
      xyz: [2.47, 2.4, 0.3]
      color: [0, 0, 1.0]
    - name: object_12
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -0.045605409]
      xyz: [2.47, 1.8, 0.3]
      color: [0, 0, 1.0]
    - name: object_13
      type: DynamicCuboid
      scale: [0.6, 0.6, 0.6]
      rpy: [0.0, 0.0, -0.010600451]
      xyz: [2.47, 1.2540823221206665, 0.3]
      color: [0, 0, 1.0]
