# # no calibration for base-arm or tool
# wood tray
# base_to_arm_transform:
#   rpy: [0, 0, 0]
#   xyz: [0.00352267, -0.00023573, 0.0128]
# gripped_object_transform:
#   rpy: [2.577042579650879, -1.5438268184661865, 0.5722295045852661]
#   xyz: [0.036378104239702225, -0.0030921208672225475, 0.3082740306854248]

base_to_arm_transform:
  rpy: [0, 0, 0]
  xyz: [0, 0, 0.0128]
gripped_object_transform:
  rpy: [0, 0, 0]
  xyz: [0.0, -0.1, 0.35]