simulation:
  robot:
    # home: [0, 0, 0, 0.5pi, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi]  # upright
    home: [0, -0, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi]  # standard
#    home: [1, -1, 0.75pi, 0.35pi, -0.65pi, 0.346pi, -0.233pi, 0.75pi, 0.32pi]  # standard
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 18 # state
      u: 9  # input
    noise:
      measurement:
        q_std_dev: 0
        v_std_dev: 0
      process:
        v_std_dev: 0
    joint_names:
      - "x_to_world_joint"
      - "y_to_x_joint"
      - "base_to_y_joint"
      - "ur10_arm_shoulder_pan_joint"
      - "ur10_arm_shoulder_lift_joint"
      - "ur10_arm_elbow_joint"
      - "ur10_arm_wrist_1_joint"
      - "ur10_arm_wrist_2_joint"
      - "ur10_arm_wrist_3_joint"
    tool_joint_name: "gripped_object_joint"
    base_joint_name: "base_to_y_joint"
    link_names:
      - "base"
      - "ur10_arm_base_link"
      - "ur10_arm_shoulder_link"
      - "ur10_arm_upper_arm_link"
      - "ur10_arm_forearm_link"
      - "ur10_arm_wrist_1_link"
      - "ur10_arm_wrist_2_link"
      - "ur10_arm_wrist_3_link"
      - "gripped_object"
    tool_link_name: "gripped_object"
    base_link_name: "base"
    base_type: omnidirectional
    urdf:
#      package: "mmseq_assets"
#      path: "thing/urdf/mm_pyb_fingers.urdf"
      package: "mmseq_assets"
      path: "thing/urdf/thing_sim.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/cartesian_base_joints.urdf.xacro"
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/end_effector_empty.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/arm_coverage.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/cameras.urdf.xacro"
      args:
        use_collision: "false"
        transform_params: "$(find mmseq_run)/config/robot/urdf_transforms.yaml"

controller:
  # robot parameters
  robot:
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 18 # state
      u: 9  # input
    x0: [ 1, -1, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi ]

    limits:
      input_rate:
        lower: [-10, -10, -10, -80, -80, -80, -80, -80, -80]
        upper: [10, 10, 10, 80, 80, 80, 80, 80, 80]
      input:
        lower: [ -2.5, -2.5, -1., -2.16, -2.16, -3.15, -3.2, -3.2, -3.2 ]
        upper: [ 2.5, 2.5, 1., 2.16, 2.16, 3.15, 3.2, 3.2, 3.2 ]
      state:
        lower: [ -10, -10, -2.pi, -0.pi, -1pi, -1pi, -1pi, -1pi, -1pi,
                 -1.1, -1.1, -2, -2, -2, -3, -3, -3, -3 ]
        upper: [ 10, 10, 2pi, 1.pi, 1pi, 1pi, 1pi, 1pi, 1pi,
                 1.1, 1.1, 2, 2, 2, 3, 3, 3, 3 ]

    link_names:
      - "base"
      - "ur10_arm_base_link"
      - "ur10_arm_shoulder_link"
      - "ur10_arm_upper_arm_link"
      - "ur10_arm_forearm_link"
      - "ur10_arm_wrist_1_link"
      - "ur10_arm_wrist_2_link"
      - "ur10_arm_wrist_3_link"
      - "gripped_object"
    tool_link_name: "gripped_object"
    base_link_name: "base"
    base_type: omnidirectional

    tool_vicon_name: "ThingContainer"

    collision_link_names:
      base:
        - "base_collision_link"
      rack:
        - "rack_collision_link"
      upper_arm:
        - "ur10_arm_upper_arm_collision_link"
        - "ur10_arm_upper_arm_collision_sphere_link1"
        - "ur10_arm_upper_arm_collision_sphere_link2"
        - "ur10_arm_upper_arm_collision_sphere_link3"
      forearm:
        - "ur10_arm_forearm_collision_link"
        - "ur10_arm_forearm_collision_sphere_link1"
        - "ur10_arm_forearm_collision_sphere_link2"
      wrist:
        - "ur10_arm_wrist1_collision_link"
        - "ur10_arm_wrist3_collision_link"
      tool:
        - "gripped_object_collision_link"


    urdf:
      package: "mmseq_assets"
      path: "thing/urdf/thing_ctrl.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/end_effector_fingers.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/collision.urdf.xacro"
      args:
        use_collision: "True"
        transform_params: "$(find mmseq_run)/config/robot/robot_transforms_real.yaml"

planner:
  motion_class_type: "MobileManipulatorPointMass"
  robot:
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 18 # state
      u: 9  # input
    x0: [ 1, -1, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi ]

    limits:
      input_rate:
        lower: [-10, -10, -10, -80, -80, -80, -80, -80, -80]
        upper: [10, 10, 10, 80, 80, 80, 80, 80, 80]
      input:
        lower: [ -2.5, -2.5, -1., -2.16, -2.16, -3.15, -3.2, -3.2, -3.2 ]
        upper: [ 2.5, 2.5, 1., 2.16, 2.16, 3.15, 3.2, 3.2, 3.2 ]
      state:
        lower: [ -10, -10, -2.pi, -0.pi, -1pi, -1pi, -1pi, -1pi, -1pi,
                 -1.1, -1.1, -2, -2, -2, -3, -3, -3, -3 ]
        upper: [ 10, 10, 2pi, 1.pi, 1pi, 1pi, 1pi, 1pi, 1pi,
                 1.1, 1.1, 2, 2, 2, 3, 3, 3, 3 ]

    link_names:
      - "base"
      - "ur10_arm_base_link"
      - "ur10_arm_shoulder_link"
      - "ur10_arm_upper_arm_link"
      - "ur10_arm_forearm_link"
      - "ur10_arm_wrist_1_link"
      - "ur10_arm_wrist_2_link"
      - "ur10_arm_wrist_3_link"
      - "gripped_object"
    tool_link_name: "gripped_object"
    base_link_name: "base"
    base_type: omnidirectional

    tool_vicon_name: "ThingContainer"

    collision_link_names:
      base:
        - "base_collision_link"
      rack:
        - "rack_collision_link"
      upper_arm:
        - "ur10_arm_upper_arm_collision_link"
        - "ur10_arm_upper_arm_collision_sphere_link1"
        - "ur10_arm_upper_arm_collision_sphere_link2"
        - "ur10_arm_upper_arm_collision_sphere_link3"
      forearm:
        - "ur10_arm_forearm_collision_link"
        - "ur10_arm_forearm_collision_sphere_link1"
        - "ur10_arm_forearm_collision_sphere_link2"
      wrist:
        - "ur10_arm_wrist1_collision_link"
        - "ur10_arm_wrist3_collision_link"
      tool:
        - "gripped_object_collision_link"


    urdf:
      package: "mmseq_assets"
      path: "thing/urdf/thing_ctrl.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/end_effector_fingers.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/collision.urdf.xacro"
      args:
        use_collision: "True"
        transform_params: "$(find mmseq_run)/config/robot/robot_transforms_real.yaml"
