simulation:
  robot:
    # home: [0, 0, 0, 0.5pi, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi]  # upright
    home: [0, -0, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi]  # standard
#    home: [1, -1, 0.75pi, 0.35pi, -0.65pi, 0.346pi, -0.233pi, 0.75pi, 0.32pi]  # standard
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 18 # state
      u: 9  # input
    noise:
      measurement:
        q_std_dev: 0
        v_std_dev: 0
      process:
        v_std_dev: 0
    joint_names:
      - "x_to_world_joint"
      - "y_to_x_joint"
      - "base_to_y_joint"
      - "ur10_arm_shoulder_pan_joint"
      - "ur10_arm_shoulder_lift_joint"
      - "ur10_arm_elbow_joint"
      - "ur10_arm_wrist_1_joint"
      - "ur10_arm_wrist_2_joint"
      - "ur10_arm_wrist_3_joint"
    tool_joint_name: "gripped_object_joint"
    base_joint_name: "base_to_y_joint"
    base_type: omnidirectional
    urdf:
#      package: "mmseq_assets"
#      path: "thing/urdf/mm_pyb_fingers.urdf"
      package: "mmseq_assets"
      path: "thing/urdf/thing_pyb.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/cartesian_base_joints.urdf.xacro"
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find mmseq_assets)/thing/xacro/end_effector_fingers.urdf.xacro"
      args:
        use_collision: "false"
        transform_params: "$(find mobile_manipulation_central)/config/null_transforms.yaml"

