# no calibration for base-arm or tool
base_to_arm_transform:
  rpy: [0, 0, 0]
  xyz: [0, 0, 0]
gripped_object_transform:
  rpy: [0, 0, 0]
  xyz: [0, -0.1, 0.35]
camera_base_transform:
  rpy: [-0.00348352, -0.00496256, 0.00719247]
  xyz: [0.40360093, 0.02389736, 0.50356121]
camera_hand_transform:
  rpy: [-2.96353683, -1.53896066,  1.37120323]
  xyz: [0.0218279,  -0.16487507,  0.11044692]