planner:
  use_joy: True
  sot_type: "SoTRal25"
  tasks:
  - frame_id: base
    name: base_local_planner
    planner_type: ROSTrajectoryPlannerOnDemand
    cruise_speed: 0.5
    yaw_speed: 0.35
    yaw_accel: 100
    tracking_err_tol: 0.75
    ref_traj_duration: 12
    intermediate_waypoints: [[[2.5, -0.0, 0.0]],
                             [[7, 1.0, 0.0]]
                             ]
    plan_on_start: True
  # - frame_id: base_link
  #   name: ee_pose_baseframe
  #   planner_type: EEPoseSE3Waypoint
  #   target_pose: [1.35, 0.17, 0.7, 1.57, 0, 1.57]
  #   hold_period: 4
  #   tracking_err_tol: 0.1
  - frame_id: base
    name: ee_pose
    planner_type: EELookAheadWorld
    default_pose: [1.35, 0.17, 0.7, 1.57, 0, 1.57]
    look_ahead_time: 8
    max_angle: 0.1 # rad
  # - frame_id: base
  #   name: ee_global_planner
  #   planner_type: EEPos3WaypointOnDemand
  #   target_waypoints: [[5., 0.4, 0.9],
  #                      [0.2, 1.1, 0.9]] # in base frame
  #   hold_period: 2
  #   tracking_err_tol: 0.3
  - frame_id: base
    name: ee_global_planner
    planner_type: EEPoseSE3WaypointOnDemand
    target_waypoints: [[3.6, -0.3, 0.85, 1.57, 0, 0],
                       [8.35, 2, 0.7, 1.57, 0, 1.57]] # in base frame
    hold_period: 4.5
    tracking_err_tol: 0.3
simulation:
  duration: 100
  robot:
    #home: [0., -0.2, 0, 0.5pi, -0.75pi, 0.75pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    home: [-0, 0, -0., 0.25pi, -0.3pi, 0.5pi, -0.25pi, 0.6pi, -0.25]

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/ral25/controller.yaml" # config/ral25/controller.yaml or config/controller/NavMPC.yaml
  - package: "mmseq_run"
    path: "config/sim/isaac_sim.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"
  - package: "mmseq_run"
    path: "config/scene/single_object.yaml"
logging:
  log_dir: "$MOBILE_MANIPULATION_CENTRAL_BAG_DIR/ral25/ee_hold/"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info
