planner:
  sot_type: "SoTRal25"
  tasks:
  - frame_id: base
    name: base_local_planner
    planner_type: ROSTrajectoryPlannerOnDemand
    cruise_speed: 0.35
    yaw_speed: 0.35
    yaw_accel: 100
    tracking_err_tol: 0.6
    ref_traj_duration: 3.5
    intermediate_waypoints: [[[1.2, -0.8, -0.3],
                              [2.35, -1.25, 0],
                              [3.5, -1.1, 1.4],
                              [4.2, 0.2, 1.65]],
                             [[4.2, 2.35, 1.78],
                              [3.6, 3.7, 2.8],
                              [2.44, 3.45, -3.11],
                              [1.21, 3.3, -2.2],
                              [1.0, 1.3, -1.51]]
                             ]
    plan_on_start: True
  # - frame_id: base_link
  #   name: ee_pose_baseframe
  #   planner_type: EEPoseSE3Waypoint
  #   target_pose: [1.35, 0.17, 0.7, 1.57, 0, 1.57]
  #   hold_period: 4
  #   tracking_err_tol: 0.1
  - frame_id: base_link
    name: ee_pose_baseframe
    planner_type: EELookAhead
    default_pose: [1.35, 0.17, 0.7, 1.57, 0, 1.57]
    look_ahead_time: 10
    max_angle: 1.06 # rad
  - frame_id: base
    name: ee_global_planner
    planner_type: EEPos3WaypointOnDemand
    target_waypoints: [[5., 0.4, 0.9],
                       [0.2, 1.1, 0.9]] # in base frame
    hold_period: 2
    tracking_err_tol: 0.3

simulation:
  duration: 100
  robot:
    #home: [0., -0.2, 0, 0.5pi, -0.75pi, 0.75pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    home: [-0, 0, -0., 0.25pi, -0.3pi, 0.5pi, -0.25pi, 0.6pi, 0.417pi]

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/ral25/controller.yaml"
  - package: "mmseq_run"
    path: "config/sim/isaac_sim.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"
  - package: "mmseq_run"
    path: "config/scene/ral25.yaml"
logging:
  log_dir: "$MOBILE_MANIPULATION_CENTRAL_BAG_DIR/Oct12/"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
