planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 1.137734874067663
    - 0.8290934256669099
    - 1.338965227489347
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 4.396131967102072
    - 0.8054876481786685
    tracking_err_tol: 0.02
