planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.08025404436011602
    - -0.5229894606472103
    - 0.4123006644330971
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 3.0264696723104882
    - -0.17353474792305446
    tracking_err_tol: 0.02
