planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -1.4504583399499282
    - -0.01207003133881013
    - 1.4121672694464478
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -4.218344151268106
    - 1.4234124313474372
    tracking_err_tol: 0.02
