planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.31814910814720765
    - -0.6652925303210346
    - -0.30579744841387746
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 3.204133408583652
    - 1.3252747286627777
    tracking_err_tol: 0.02
