planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -1.0565813911552822
    - 0.42910743624911574
    - 1.4767476761184524
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -0.5368319081615646
    - 2.395673240692418
    tracking_err_tol: 0.02
