planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -0.5251264333280818
    - -0.07725643419495598
    - -0.31211897848311665
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 2.167330200110613
    - -1.3588035802246985
    tracking_err_tol: 0.02
