planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -0.3135738704188428
    - -0.18949334618037883
    - -0.4597849076250129
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 3.17278837222172
    - -0.08660692765540604
    tracking_err_tol: 0.02
