planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -0.3159870884905614
    - -0.5532602188581726
    - -0.23640427519121565
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -1.1155781108400027
    - 2.609897694456836
    tracking_err_tol: 0.02
