planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -0.016041565610351402
    - 0.07671636344248842
    - -0.2596068775736622
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 1.762923622930666
    - 1.720713069696836
    tracking_err_tol: 0.02
