planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.5949697348932803
    - -1.864614290832995
    - 0.4229587245058637
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 3.0919673004572843
    - 0.4297875719891966
    tracking_err_tol: 0.02
