planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.17285438545704854
    - 0.022077610699296528
    - 1.165239691095876
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 2.4911339072709855
    - -2.4462617484420592
    tracking_err_tol: 0.02
