planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -1.915157261353048
    - 0.38218452551572646
    - 1.4535221763806743
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -2.1200560483128306
    - -2.6505927664493076
    tracking_err_tol: 0.02
