planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.7948452858926757
    - 1.0031034969740837
    - 1.3893378340991678
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -1.6755534211487024
    - 2.471184770988666
    tracking_err_tol: 0.02
