planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -1.1142892026198636
    - 0.5349129413720303
    - -0.22905187155509954
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -3.3101382789250104
    - -0.49778393767764506
    tracking_err_tol: 0.02
