planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.5818294141576668
    - -0.5388336876248653
    - 0.6625457452717174
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -0.6877048536133059
    - -3.9005764774756853
    tracking_err_tol: 0.02
