planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.5091700295747021
    - -0.7351396451006593
    - 0.8989585506350086
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 1.4553663680746898
    - -2.9677896239833306
    tracking_err_tol: 0.02
