planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - -0.6634719280110122
    - 0.2771077823541503
    - 0.8952623918545297
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -1.6376353713160077
    - -1.4126450006843279
    tracking_err_tol: 0.02
