planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0.3304380130431951
    - 1.2999351246119935
    - -0.2421474046902934
    tracking_err_tol: 0.02
  - frame_id: EE
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -1.2819497168972993
    - 3.15897291749555
    tracking_err_tol: 0.02
