simulation:
  # Isaac Sim Simulated Cameras
  cameras:
    - name: "camera_base_rgb"
      type: "RGBCamera"
      prim_path: "/thing/base_link/camera_base/camera_base_rgb"
      params:
        package: "mm_run"
        path: "config/sensor/femto_bolt_rgb.yaml"
      translation: [0.40360093, 0.02389736, 0.50 ]
      orientation: [ 0.99998895 ,  -0.00173282, -0.00248752,  0.00359189]
      ros_topic_name_space: "camera_base"
    - name: "camera_base_tof"
      type: "ToFCamera"
      prim_path: "/thing/base_link/camera_base/camera_base_tof"
      params:
        package: "mm_run"
        path: "config/sensor/femto_bolt_depth.yaml"
      translation: [0.40360093, 0.02389736, 0.50 ]
      orientation: [ 0.99998895 ,  -0.00173282, -0.00248752,  0.00359189]
      ros_topic_name_space: "camera_base"
    - name: "camera_arm_rgb"
      type: "RGBCamera"
      prim_path: "/thing/gripper/camera_arm/camera_arm_rgb"
      params:
        package: "mm_run"
        path: "config/sensor/femto_bolt_rgb.yaml"
      translation: [0.0218279,  -0.16487507,  0.11044692]
      orientation: [ -0.48820154, 0.5146015,   0.50084812,  0.49597955   ]
      ros_topic_name_space: "camera_hand"
    - name: "camera_arm_tof"
      type: "ToFCamera"
      prim_path: "/thing/gripper/camera_arm/camera_arm_tof"
      params:
        package: "mm_run"
        path: "config/sensor/femto_bolt_depth.yaml"
      translation: [0.0218279,  -0.16487507,  0.11044692]
      orientation: [ -0.48820154, 0.5146015,   0.50084812,  0.49597955   ]
      ros_topic_name_space: "camera_hand"
