# Parameters given by the Orbbec Femto Mega USD model
height: 720
width: 1280
distortion_model: "pinhole"
D: []
K: [763.3027954101562, 0.0, 640.0, 0.0, 763.302734375, 360.0, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [763.3027954101562, 0.0, 640.0, 0.0, 0.0, 763.302734375, 360.0, 0.0, 0.0, 0.0, 1.0, 0.0]

# Doc: https://d1cd332k3pgc17.cloudfront.net/wp-content/uploads/2023/08/ORBBEC_Datasheet_Femto-Bolt-1.pdf
clipping_range: [0.25, 3.0]          # WFOV Unbinned.
frequency: 10                        # fps
