# Parameters given by the Orbbec Femto Mega USD model
height: 720
width: 1280
distortion_model: "pinhole"
D: []
K: [763.3027954101562, 0.0, 640.0, 0.0, 763.302734375, 360.0, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [763.3027954101562, 0.0, 640.0, 0.0, 0.0, 763.302734375, 360.0, 0.0, 0.0, 0.0, 1.0, 0.0]

clipping_range: [0.05, 10000]
frequency: 10  # fps
