planner:
  sot_type: "SoTStatic"
  tasks:
  - frame_id: base
    name: Base Position
    planner_type: BaseSingleWaypoint
    initial_pos: [0,0]
    target_pos:
    - 6.0
    - 0.0
    cruise_speed: 0.5
    tracking_err_tol: 0.4
  # - frame_id: base
  #   name: Base Position
  #   planner_type: BasePosTrajectoryLine
  #   initial_pos: [1,0.]
  #   target_pos:
  #   - 2.5
  #   - 0.
  #   cruise_speed: 1.0
  #   tracking_err_tol: 0.4

controller:
  home: "default"
  sdf_collision_avoidance_enabled: False
  self_collision_avoidance_enabled: False
  static_obstacles_collision_avoidance_enabled: True

  collision_constraint_type: "SignedDistanceConstraintCBF" # SignedDistanceConstraint or SignedDistanceConstraintCBF 
  type: "STMPC"
  collision_constraints_softend:
    self: False
    sdf: False
    static_obstacles: False

simulation:
  static_obstacles:
    enabled: True

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/simple_obstacles.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF2D.yaml"

logging:
  log_dir: "/home/tracy/PhD/data/2d_collision"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
