planner:
  sot_type: "SoTStatic"
  tasks:
  - name: "EE Pos 1"
    planner_type: "EESimplePlanner"
    frame_id: "EE"
    initial_pos: [0.0, -0.0, 0.0]
    target_pos: [0.0, 1.0, 0.0]
    hold_period: 3.
    tracking_err_tol: 0.02
    cruise_speed: 0.5

simulation:
  robot:
    home: [0, -0, 0, 0.25pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi]  # standard
  static_obstacles:
    enabled: True

controller:
  home: "default"
  sdf_collision_avoidance_enabled: False
  self_collision_avoidance_enabled: False
  static_obstacles_collision_avoidance_enabled: True
  
  collision_constraints_softend:
    self: False
    sdf: False
    static_obstacles: False
  collision_cbf_gamma: 2
  collision_constraint_type: "SignedDistanceConstraintCBF" # SignedDistanceConstraint or SignedDistanceConstraintCBF 
  type: "STMPC"
  acados:
    ocp_solver_options:
      nlp_solver_max_iter: 100
      qp_solver_warm_start: 1
    slack_enabled:
      x: True
      x_e: True
      h_0: True
      h: True
      h_e: False

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/simple_obstacles.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"

logging:
  log_dir: "/home/tracy/PhD/data/3d_collision"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
