planner:
  sot_type: "SoTStatic"
  tasks:
  # - name: "EE Pos 1"
  #   planner_type: "EEPosTrajectoryLine"
  #   frame_id: "base"
  #   initial_pos: [0.7, -0.91, 0.7]
  #   target_pos: [1.0, 0.5, 0.5]
  #   hold_period: 3.
  #   tracking_err_tol: 0.02
  #   cruise_speed: 0.5
  # - frame_id: base
  #   name: Base Position
  #   planner_type: BaseSingleWaypoint
  #   target_pos:
  #   - 0
  #   - 0.
  #   tracking_err_tol: 0.02
  - frame_id: base
    name: Base Position
    planner_type: BasePosTrajectoryLine
    initial_pos: [0,0]
    target_pos:
    - 1.0
    - 0.5
    cruise_speed: 1.0
    tracking_err_tol: 0.4
  - frame_id: base
    name: Base Position
    planner_type: BasePosTrajectoryLine
    initial_pos: [1,0.5]
    target_pos:
    - 2.5
    - 0.5
    cruise_speed: 1.0
    tracking_err_tol: 0.4
  - frame_id: base
    name: Base Position
    planner_type: BasePosTrajectoryLine
    initial_pos: [2.5,0.5]
    target_pos:
    - 4.0
    - 0.0
    cruise_speed: 1.0
    tracking_err_tol: 0.4

controller:
  home: "default"
  sdf_collision_avoidance_enabled: True
  type: "STMPC"

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"

logging:
  log_dir: "/home/tracy/PhD/data/3d_collision"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
