planner:
  sot_type: "SoTStatic"
  tasks:
  - frame_id: base
    name: Base Position
    planner_type: ROSTrajectoryPlanner
    cruise_speed: 0.35
    yaw_speed: 0.5
    yaw_accel: 0.9
    tracking_err_tol: 0.4
    ref_traj_duration: 1.5
  - frame_id: base
    name: EE Position BaseFrame
    planner_type: EESimplePlannerBaseFrame
    target_pos: [1.458, 0.17, 0.7] # in base frame
    hold_period: 4
    tracking_err_tol: 0.4
simulation:
  duration: 100
  robot:
    #home: [0., -0.2, 0, 0.5pi, -0.75pi, 0.75pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    home: [-0, 0, -0., 0.25pi, -0.3pi, 0.5pi, -0.25pi, 0.6pi, 0.417pi]

controller:
  home: "default"
  sdf_collision_avoidance_enabled: True
  self_collision_avoidance_enabled: True
  static_obstacles_collision_avoidance_enabled: True
  base_pose_tracking_enabled: True

  collision_constraint_type: "SignedDistanceConstraint" # SignedDistanceConstraint or SignedDistanceConstraintCBF 
  type: "STMPC"
  collision_constraints_softend:
    self: False
    sdf: False
    static_obstacles: False
  collision_cbf_gamma: 0.9
  
  acados:
    name: MMCtrlSLAM
    ocp_solver_options:
      nlp_solver_max_iter: 100
      qp_solver_warm_start: 2
    slack_enabled:
      x: True
      x_e: True
      u: False
      h_0: True
      h: True
      h_e: True
include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/isaac_sim.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"

logging:
  log_dir: "$MOBILE_MANIPULATION_CENTRAL_BAG_DIR/3d_collision/"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
