planner:
  sot_type: "SoTStatic"
  tasks:
  - name: "EE Pos 1"
    planner_type: "EEPosTrajectoryLine"
    frame_id: "EE"
    initial_pos: [0.0, -0.0, 0.0]
    target_pos: [-0.0, 4.0, 0.0]
    hold_period: 3.
    tracking_err_tol: 0.02
    cruise_speed: 0.75
  # - frame_id: base
  #   name: Base Position
  #   planner_type: BasePosTrajectoryLine
  #   initial_pos: [0,0]
  #   target_pos:
  #   - 3.0
  #   - 0.0
  #   cruise_speed: 0.2
  #   tracking_err_tol: 0.4
  - frame_id: base
    name: Base Position
    planner_type: BasePoseTrajectoryLine
    initial_pose: [0,0,0]
    target_pose:
    - 0
    - 4.
    - 0
    cruise_speed: 1.0
    tracking_err_tol: 0.4
    yaw_speed: 0.2
simulation:
  robot:
    #home: [0., -0.2, 0, 0.5pi, -0.75pi, 0.75pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    home: [0.25, 0.0, -0.0, 0.2pi, -0.25pi, 0.5pi, -0.25pi, 0.6pi, 0.417pi]

controller:
  home: "default"
  sdf_collision_avoidance_enabled: True
  self_collision_avoidance_enabled: False
  static_obstacles_collision_avoidance_enabled: False

  collision_constraint_type: "SignedDistanceConstraint" # SignedDistanceConstraint or SignedDistanceConstraintCBF 
  type: "STMPC"
  collision_constraints_softend:
    self: False
    sdf: False
    static_obstacles: False
  collision_cbf_gamma: 0.9
  
  acados:
    ocp_solver_options:
      nlp_solver_max_iter: 100
      qp_solver_warm_start: 2
    slack_enabled:
      x: True
      x_e: True
      u: False
      h_0: True
      h: True
      h_e: True
include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/isaac_sim.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"

logging:
  log_dir: "$MOBILE_MANIPULATION_CENTRAL_BAG_DIR/3d_collision/Sep9"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
