planner:
  sot_type: "SoTStatic"
  tasks:
    - name: "EE Pos 1"
      planner_type: "EESimplePlanner"
      frame_id: "EE"
      target_pos: [0., 0., 0.]
      hold_period: 3.
      tracking_err_tol: 0.02
    - frame_id: base
      name: Base Position
      planner_type: BasePosTrajectoryLine
      initial_pos: [0,0]
      target_pos:
      - 4.0
      - 0.0
      cruise_speed: 1.0
      tracking_err_tol: 0.2
      yaw_speed: 1
    # - name: "Base Pos 1"
    #   planner_type: "BaseSingleWaypoint"
    #   frame_id: "base"
    #   target_pos: [4.0, 0.]
    #   tracking_err_tol: 0.25

controller:
  home: "default"
  self_collision_avoidance_enabled: True
  sdf_collision_avoidance_enabled: False
  type: "STMPC"


simulation:
  duration: 10

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"
  - package: "mmseq_run"
    path: "config/robot/thing_collision_pairs.yaml"
logging:
  log_dir: "$MOBILE_MANIPULATION_CENTRAL_BAG_DIR/self_collision/Sep11/"
  log_level: 4 # 0 - not set, 10 - debug, 20 - info
