planner:
  sot_type: "SoTStatic"
  tasks:
   # - name: "EE Pos 1"
   #   planner_type: "EESimplePlanner"
   #   frame_id: "EE"
   #   target_pos: [0., -0.0, 0.]
   #   hold_period: 3.
   #   tracking_err_tol: 0.02
   - name: "Base Pos 1"
     planner_type: "BaseSingleWaypoint"
     frame_id: "base"
     target_pos: [-0.0, 0.]
     tracking_err_tol: 0.25

   - name: "EE Circle 1 "
     planner_type: "EEPosTrajectoryCircle"
     frame_id: "EE"
     period: 5
     round: 3
     plane_id: [1, 2]
     center: [0., 0.5, 0.2]
     radius: 0.5
     angular_offset: 1.1pi
     tracking_err_tol: 0.02
    # - name: "Base Circle 1 "
    #   planner_type: "BasePosTrajectoryCircle"
    #   frame_id: "base"
    #   period: 3.
    #   round: 2
    #   plane_id: [1, 2 ]
    #   center: [ 0.5, 0.0]
    #   radius: 0.5
    #   angular_offset: 1.0pi
    #   tracking_err_tol: 0.02

controller:
  mpc_rate: 10 #hz
  penalize_du: False
  ST_MaxIntvl: 1
  cost_params:
    EEPos3:
      Qk: 5.
      P: 10.
    BasePos2:
      Qk: 5.
      P: 10.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.01
      Qvb: 0.01
      Qua: 0.01
      Qub: 0.05
      Qdua: 0.
      Qdub: 0.

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/HTMPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/debug"
  log_level: 4 # 0 - not set, 10 - debug, 20 - info
