planner:
  sot_type: "SoTStatic"
  tasks:
  # - frame_id: base
  #   name: Base Pose
  #   planner_type: BaseSingleWaypointPose
  #   target_pose: [0,0,3.13]
  #   tracking_err_tol: 0.4
  #   ref_traj_duration: 1.5
  - frame_id: base
    name: EE Position BaseFrame
    planner_type: EESimplePlannerBaseFrame
    target_pos: [1.458, 0.17, 0.7]
    hold_period: 4
    tracking_err_tol: 0.4
  # - frame_id: base
  #   name: Base Position
  #   planner_type: BasePosTrajectoryLine
  #   initial_pos: [0,0]
  #   target_pos:
  #   - 2.5
  #   - 0.4
  #   cruise_speed: 1.0
  #   tracking_err_tol: 0.2
  # - frame_id: base
  #   name: Base Position
  #   planner_type: BasePosTrajectoryLine
  #   initial_pos: [2.5,0.4]
  #   target_pos:
  #   - 5.
  #   - 0.25
  #   cruise_speed: 1.0
  #   tracking_err_tol: 0.02
   # - name: "EE Circle 1 "
   #   planner_type: "EEPosTrajectoryCircle"
   #   frame_id: "EE"
   #   period: 5
   #   round: 3
   #   plane_id: [1, 2]
   #   center: [0., 0.5, 0.2]
   #   radius: 0.5
   #   angular_offset: 1.1pi
   #   tracking_err_tol: 0.02
  # - name: "Base Circle 1 "
  #   planner_type: "BasePosTrajectoryCircle"
  #   frame_id: "base"
  #   period: 10.
  #   round: 2
  #   plane_id: [1, 2 ]
  #   center: [ -0.5, 0.0]
  #   radius: 0.5
  #   angular_offset: 0.0pi
  #   tracking_err_tol: 0.02
  # - frame_id: base
  #   name: Base Position
  #   planner_type: BasePoseTrajectoryLine
  #   initial_pose: [0,0,0]
  #   target_pose:
  #   - 2.5
  #   - 0.4
  #   - 0.7
  #   cruise_speed: 1.0
  #   yaw_speed: 0.5
  #   tracking_err_tol: 0.2
simulation:
  robot:
    #home: [0., -0.2, 0, 0.5pi, -0.75pi, 0.75pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    home: [0.0, 0.0, 0.5pi, 0.2pi, -0.25pi, 0.5pi, -0.25pi, 0.6pi, 0.417pi]

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"

logging:
  log_dir: "/home/tracy/PhD/data/Sep12/"
  log_level: 10 # 0 - not set, 10 - debug, 20 - info
