planner:
  sot_type: "SoTStatic"
  tasks:
    - name: "whole_body"
      planner_type: "SequentialPlanner"
      N: 500
      dt: 0.01
      target_points: [[1, 2, 1], [4, 4, 1], [1, 2, 1]]
      prediction_horizon: 3
      initialization: "Pontryagin" #Pontryagin or InverseKinematics
      obstacle_avoidance: True
      motion_class_type: "MobileManipulatorPointMass"
      tracking_err_tol: 0.02
      motion_class_config_file: 
          package: "mmseq_run"
          path: "config/robot/default_thing_whole_body.yaml"
      # - name: "whole_body"
      #   planner_type: "CPCPlanner"
      #   N: 200
      #   dt: 0.01
      #   target_points: [[1, 2, 1], [4, 4, 1]]
      #   prediction_horizon: 2
      #   initialization: "Pontryagin"
      #   obstacle_avoidance: True
      #   cpc_tolerance: 0.0001
      #   d_tol: 0.1
      #   motion_class_type: "MobileManipulatorPointMass"
      #   tracking_err_tol: 0.01
      #   motion_class_config_file: 
      #       package: "mmseq_run"
      #       path: "config/robot/default_thing_whole_body.yaml"
controller:
  home: "default"
  self_collision_avoidance_enabled: True
  sdf_collision_avoidance_enabled: False
  type: "STMPC"


simulation:
  duration: 10

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"
  - package: "mmseq_run"
    path: "config/map/SDF3D.yaml"

logging:
  log_dir: "/home/ubuntu/"
  log_level: 4 # 0 - not set, 10 - debug, 20 - info
